num1=int(input("Enter a number:"))
num2=int(input("Enter a number:"))
print("Addition:",num1+num2)
print("Subtraction:",num1-num2)
print("Multiplication:",num1*num2)
print("Division:",num1/num2)
print("Floor Division:",num1//num2)
print("Modulus:",num1%num2)
print("Power:",num1**num2)